[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.build]
cmds = [
  "python3 -m pip install -r backend/requirements.txt",
  "cd database && python3 generate_db.py && cp graph.db ../backend/"
]

[start]
cmd = "cd backend && python3 -m gunicorn --bind 0.0.0.0:$PORT server:app"
